import os
import asyncpg
from typing import Optional
import logging

logger=logging.getLogger(__name__)

# Global variable to hold the connection pool after startup
_pool: Optional[asyncpg.Pool]=None

# Read DB url from the env variable or use local db
POSTGRES_DSN= os.getenv(
    "POSTGRES_DSN",
    "postgresql://postgres:postgres@localhost:5432/xai_metrics",
)

# SQL command that PostgreSQL understands
# This creates our metrics table if it doesn't already exist
# this command will then be sent to Postgres
CREATE_TABLES_SQL = """
CREATE TABLE IF NOT EXISTS stress_test_metrics (

    -- Auto-incrementing unique ID
    id SERIAL PRIMARY KEY,

    -- Unique identifier for a test run
    run_id TEXT NOT NULL,

    -- Type of stress test
    -- Example: adversarial, hallucination, paraphrase
    category TEXT NOT NULL,

    -- Prompt sent to the LLM
    prompt TEXT NOT NULL,

    -- Response generated by the LLM
    response TEXT NOT NULL,

    -- Numerical robustness score
    score FLOAT,

    -- Did the model pass the test?
    passed BOOLEAN,

    -- Average confidence during generation
    confidence FLOAT,

    -- Flexible JSON field for storing extra information
    metadata JSONB,

    -- Automatically stores insertion time
    created_at TIMESTAMPTZ DEFAULT NOW()
);
"""

# create the connection pool when application starts
async def connect_postgres():
    global _pool
    logger.info("Connecting to PostgreSQL pool")

    #creating a reusable bucket of db connections
    _pool = await asyncpg.create_pool(
        POSTGRES_DSN,
        min_size=2,
        max_size=10
    )

    # Borrow one connection from the pool
    # and execute our table creation SQL
    async with _pool.acquire() as conn:
        # send the CREATE TABLE command to PostgreSQL
        await conn.execute(CREATE_TABLES_SQL)

    logger.info("Connection pool initialized")

# closing all db connections when shutting down
async def disconnect_postgres():
    global _pool
    if _pool:
        await _pool.close()
        logger.info("Pool disconnected")
    
# giving pool access to the other parts of the app
def get_pool() -> asyncpg.Pool:
    # safety check sp routes dont use an uninitialized pool
    if _pool is None:
        raise RuntimeError(
            " CRITICAL: PostgreSQL pool is not initialized"
        )
    
    # returning the active connection pool
    return _pool


async def insert_metric(
    run_id: str,
    category: str,
    prompt: str,
    response: str,
    score: float,
    passed: bool,
):
    """
    Store one stress test result in PostgreSQL.

    Think:
    One prompt tested
        ↓
    One result generated
        ↓
    One row inserted
    """

    # get access to the connection pool
    pool=get_pool()

    # borrowing 1 connection temporarily
    async with pool.acquire() as conn:
        #Execute INSERT query
        await conn.execute(
            """
            INSERT INTO stress_test_metrics
            (
                run_id,
                category,
                prompt,
                response,
                score,
                passed
            )
            VALUES
            (
                $1,
                $2,
                $3,
                $4,
                $5,
                $6
            )
            """,
            run_id,
            category,
            prompt,
            response,
            score,
            passed
        )

async def get_metrics_for_run(run_id: str):
    """
    Retrieve all metrics belonging to a specific run.

    Example:
        run_001

    Returns every stress test result generated
    during that run.
    """

    pool=get_pool()

    # borrow connection from pool
    async with pool.acquire() as conn:
        # fetch rows from PostgreSQL
        rows= await conn.fetch(
            """
            SELECT *
            FROM stress_test_metrics
            WHERE run_id = $1
            ORDER BY created_at
            """,
            run_id 
        )
    
    # Convert asyncpg Record objects into dictionaries
    return [dict(row) for row in rows]

# not a CRUD function but a Database Query
async def get_run_summary(run_id: str):
    """
    Returns dashboard statistics
    for a particular stress test run.
    """   

    pool=get_pool()
    async with pool.acquire() as conn:
        rows= await conn.fetch(
             """
            SELECT
                category,
                COUNT(*) AS total_tests,
                AVG(score) AS average_score
            FROM stress_test_metrics
            WHERE run_id = $1
            GROUP BY category
            """,
            run_id
        )
    return [dict(row) for row in rows]
